# reference link: https://github.com/settings/installations/32352506

repository:
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  homepage: https://example.github.io/

Labels: define labels for Issues and Pull Requests
labels:
  ################## github common start ##################
  - name: bug11
    color: '#d73a4a'



